# Generated by Django 5.2.1 on 2025-05-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_duser_region_component_componentregioninfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('regions', models.ManyToManyField(related_name='cars', to='common.region')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='common.car'),
            preserve_default=False,
        ),
    ]
